If anyone is getting this message while loading the task .ipynb file "Sorry, something went wrong. Reload?" when viewing an *.ipynb on a GitHub blob page.

 - Probably a problem with the GitHub notebook viewing tool - sometimes github fails to render the ipynb notebooks, I believe that is some temporary (and recurring) issue with their backend

Try to open that notebook that you want using nbviewer online, you don't need to install it.

 - Open "https://nbviewer.jupyter.org/"
 - Paste the link to your notebook, (e.g. "https://github.com/Vishwa-Patel-2405/The-Sparks-Foundation-Tasks/blob/main/Other%20Domain%20Tasks/Task-1_Optical_Character_Recognition.ipynb") there and then you get "https://nbviewer.jupyter.org/github/Vishwa-Patel-2405/The-Sparks-Foundation-Tasks/blob/main/Other%20Domain%20Tasks/Task-1_Optical_Character_Recognition.ipynb"
